-- ============================================================
-- 自习室房间表（study_rooms）· CloudBase PostgreSQL
-- 供 App / Web / 小程序 三端共用，实现房间数据互通。
-- 幂等：可重复执行。
-- ============================================================

CREATE TABLE IF NOT EXISTS public.study_rooms (
  id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name          VARCHAR(100) NOT NULL,
  theme         VARCHAR(32)  NOT NULL DEFAULT '共学',
  host_id       VARCHAR(64)  NOT NULL,
  host_name     VARCHAR(64)  NOT NULL DEFAULT '',
  slogan        VARCHAR(200) NOT NULL DEFAULT '',
  members       JSONB        NOT NULL DEFAULT '[]'::jsonb,
  online_count  INT          NOT NULL DEFAULT 1,
  hot_score     INT          NOT NULL DEFAULT 0,
  today_minutes INT          NOT NULL DEFAULT 0,
  created_at    BIGINT       NOT NULL,
  updated_at    BIGINT       NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_study_rooms_created_at ON public.study_rooms (created_at DESC);
CREATE INDEX IF NOT EXISTS idx_study_rooms_host_id ON public.study_rooms (host_id);

ALTER TABLE public.study_rooms ENABLE ROW LEVEL SECURITY;
GRANT SELECT ON public.study_rooms TO anon, authenticated;
GRANT INSERT, UPDATE, DELETE ON public.study_rooms TO service_role;

DROP POLICY IF EXISTS study_rooms_select_all ON public.study_rooms;
CREATE POLICY study_rooms_select_all ON public.study_rooms FOR SELECT USING (true);

DROP POLICY IF EXISTS study_rooms_write_admin ON public.study_rooms;
CREATE POLICY study_rooms_write_admin ON public.study_rooms
  FOR ALL USING (auth.role() = 'service_role') WITH CHECK (auth.role() = 'service_role');
